<?php

/**
 *
 * @file
 * Contains owlcarousel.module..
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\owlcarousel\OwlCarouselGlobal;
use Drupal\owlcarousel\OwlCarouselView;

/**
 * Implements hook_help().
 */
function owlcarousel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the owl module.
    case 'help.page.owlcarousel':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OWL Carousel: Download code at: https://github.com/tabvn/owl') . '</p>';
      $output .= '<p>' . t('Video tutorial how to install: https://www.youtube.com/watch?v=PzBMJqkNHQ0') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function owlcarousel_theme() {
  return [
    'owlcarousel' => [
      'variables' => [
        'items' => NULL,
        'settings' => NULL
      ]
    ],
    'owlcarousel_views' => [
      'preprocess functions' => [
        'template_preprocess_owlcarousel_views',
        'template_preprocess_owlcarousel_views_view'
      ],
      'file' => 'owlcarousel.theme.inc'
    ]
  ];
}

/**
 * Themeable for owlcarousel.
 */
function template_preprocess_owlcarousel(&$variables) {
  // $items = $variables['items'];
  
  // $settings = OwlCarouselGlobal::formatSettings($variables['settings']);
  
  // $variables['attributes']['class'][] = 'owl-slider-wrapper';
  // $variables['attributes']['class'][] = 'owl-carousel';
  // $variables['attributes']['data-settings'] = json_encode($settings);
  
  // $html = '';
  // if (!empty($items)) {
  // $i = 0;
  // foreach ($items as $item) {
  // $html .= '<div class="owl-item-inner owl-item-inner' . $i . '">' .
  // render($item) . '</div>';
  // $i++;
  // }
  // }
  // $output = [
  // '#type' => 'markup',
  // '#markup' => $html
  // ];
  // $variables['output'] = render($output);
}

/**
 * Convert a string of settings to array.
 *
 * @param string $str
 *        String to be converted to array.
 *        
 * @return array Converted array.
 */
function _owlcarousel_string_to_array($str) {
  $str = trim($str);
  $str = str_replace('[', '', $str);
  $str = str_replace(']', '', $str);
  $str = explode(',', $str);
  
  return $str;
}
